Repository WorkQuest/Website-platform, pull requests merged in 2021-12, with the labels that each got.

#289 hotfix/16452 workers/id page add worker info
  components/CtmModal/CtmModalWelcome/index.vue
  components/CtmModal/index.vue
  components/app/GmapSearch/index.vue
  components/app/pages/profile/tabs/portfolio.vue
  components/app/pages/profile/tabs/reviews.vue
  components/app/panels/questPanel.vue
  locales/en.json
  pages/my.vue
  pages/profile/_id/index.vue
  pages/quests/_id/index.vue
  pages/quests/index.vue
  pages/workers/_id/index.vue
  pages/workers/index.vue
  store/modals/actions.js
  store/modals/getters.js
  store/modals/modals.js
  store/modals/mutations.js
  store/modals/state.js
  store/quests/actions.js
  store/quests/getters.js
Labels: CheckNeeded!

#306 feature/17069 on quests/_id Quest Logic hotfix
  components/CtmModal/CtmModalAreYouSureDeleteQuest/index.vue
  components/CtmModal/CtmModalSendARequest/index.vue
  components/CtmModal/CtmModalSharing/index.vue
  components/app/GmapSearch/index.vue
  components/app/info/index.vue
  components/app/pages/common/quests.vue
  components/app/pages/quests_id/employer.vue
  components/app/pages/quests_id/worker.vue
  components/app/panels/questPanel.vue
  components/ui/QuestDD/index.vue
  locales/en.json
  pages/my.vue
  pages/quests/_id/index.vue
  store/quests/actions.js
  store/quests/getters.js
  store/quests/mutations.js
  store/quests/state.js
  utils/enums.js
Labels: Need fix, in progress

#345 hotfix/18742/portfolio bug fix
  components/CtmModal/CtmModalEditCase/index.vue
  components/app/pages/profile/tabs/portfolio.vue
  components/ui/BaseTextarea/index.vue
  store/user/state.js
Labels: CheckNeeded!

#346 create quest for employe
  components/app/info/emptyData.vue
  middleware/employer-role.js
  pages/create-quest.vue
  pages/my.vue
  pages/quests/_id/index.vue
  pages/quests/index.vue
  utils/enums.js
Labels: in progress

#350 feature/19008/component_status add item-rating on quests and employer
  components/app/info/item-rating.vue
  components/app/pages/common/quests.vue
  components/app/pages/quests_id/employer.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
Labels: CheckNeeded!
