Repository WorkQuest/Website-platform, pull requests merged in 2022-03, with the labels that each got.

#496 fix/22012/number fix number change
  components/CtmModal/CtmModalSmsVerification/index.vue
Labels: CheckNeeded!

#498 fix/23425/profile_rang fix css
  components/app/CardQuest.vue
  components/app/info/item-rating.vue
Labels: CheckNeeded!

#500 fix/23490/quest_card style and small logic fix in CardQuest.vue
  components/app/CardQuest.vue
Labels: CheckNeeded!

#497 feat/19535/WQ-modal-fix fix input
  components/ui/BaseInput/index.vue
  pages/messages/index.vue
Labels: CheckNeeded!

#481 Feature/22366/info cluster
  components/app/GMapInfoBlock.vue
  components/app/GMapLoader.vue
  components/app/GoogleMapLoader.vue
  pages/my.vue
  pages/quests/_id/index.vue
  plugins/injectComponents.js
  store/google-map/actions.js
Labels: CheckNeeded!

#504 fix/dispute_warning add function in disputes/state.js
  store/disputes/state.js
Labels: CheckNeeded!

#499 Feature/21064/pension history table
  components/CtmModal/CtmModalTakeWithdraw/index.vue
  components/ui/BaseTable/index.vue
  locales/en.json
  pages/pension/my/index.vue
  store/wallet/actions.js
  store/wallet/getters.js
  store/wallet/mutations.js
  store/wallet/state.js
  utils/enums.js
Labels: CheckNeeded!

#505 Feature/22506/wallet update
  components/CtmModal/CtmModalCollateralTransaction/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/index.vue
  components/app/pages/wallet/CollateralTable.vue
  locales/en.json
  pages/wallet.vue
  store/modals/modals.js
  store/wallet/actions.js
  utils/enums.js
Labels: CheckNeeded!

#509 template fix
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/collateral/index.vue
Labels: CheckNeeded!

#516 Feature/23305 calc2
  components/CtmModal/CtmModalGetWUSD/index.vue
  components/app/Header/index.vue
  components/app/panels/filters.vue
  components/ui/BaseDD/index.vue
  components/ui/BaseInput/index.vue
  layouts/auth.vue
  layouts/confirmPassword.vue
  layouts/default.vue
  layouts/guest.vue
  layouts/role.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/collateral/index.vue
  pages/create-quest.vue
  pages/sign-in.vue
  plugins/injectComponents.js
  plugins/vee-validate.js
  store/collateral/actions.js
  utils/wallet.js
Labels: CheckNeeded!

#518 Upgrade/24163/users rating
  components/CtmModal/CtmModalInvitation/index.vue
  components/app/CardQuest.vue
  components/app/GMapInfoBlock.vue
  components/app/info/item-rating.vue
  components/app/pages/common/employeeCard.vue
  components/app/pages/common/userInfo.vue
  components/app/pages/quests_id/WorkersList.vue
  components/app/panels/filters.vue
  pages/quests/_id/index.vue
  store/disputes/state.js
  store/user/state.js
  utils/enums.js
Labels: CheckNeeded!

#519 fix/rating_style fix status__level
  components/app/info/item-rating.vue
Labels: CheckNeeded!

#501 feature/23305-collateral contract logic
  .github/workflows/main.yml
  abi/abi.js
  components/CtmModal/CtmModalGetWUSD/index.vue
  components/ui/BaseInput/index.vue
  locales/en.json
  nuxt.config.js
  plugins/vee-validate.js
  store/collateral/actions.js
  utils/enums.js
  utils/wallet.js
Labels: CheckNeeded!

#515 added func scroll to top in main.js, added logic on guests page (user…
  layouts/default.vue
  layouts/guest.vue
  pages/mining/_id/index.vue
  pages/my.vue
  pages/profile/_id/index.vue
  pages/quests/index.vue
  pages/workers/index.vue
  plugins/main.js
Labels: paused

#531 fix/24820/lending
  components/CtmModal/CtmModalClaimRewards/index.vue
  components/CtmModal/CtmModalConfirmDetails/index.vue
  components/CtmModal/CtmModalConfirmLoanDetails/index.vue
  components/CtmModal/CtmModalCreditingDeposit/index.vue
  components/CtmModal/CtmModalCreditingLoan/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/crediting/1/_id/index.vue
  pages/crediting/1/index.vue
  pages/crediting/_id/index.vue
  pages/crediting/index.vue
Labels: in progress

#534 fix/24972/curr-lang-in-store
  components/app/Header/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/sumsub.vue
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
Labels: CheckNeeded!

#522 Feature/24434/referral page
  .github/workflows/main.yml
  abi/abi.js
  assets/scss/vars.scss
  components/CtmModal/CtmModalReferralClaim/index.vue
  components/CtmModal/CtmModalStatus/index.vue
  components/CtmModal/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  nuxt.config.js
  pages/referral.vue
  pages/sign-in.vue
  pages/sign-up.vue
  plugins/connection.js
  plugins/main.js
  store/modals/modals.js
  store/referral/actions.js
  store/referral/getters.js
  store/referral/mutations.js
  store/referral/state.js
  store/user/getters.js
  store/user/state.js
  utils/referral-constants.js
Labels: in progress

#538 hotfix/24820/lending small adaptive fix
  pages/crediting/_id/index.vue
Labels: CheckNeeded!

#527 Hotfix/22729/working-bridge
  abi/abi.js
  components/CtmModal/CtmModalSwap/index.vue
  components/CtmModal/CtmModalSwapInfo/index.vue
  pages/crosschain/index.vue
  store/defi/actions.js
  store/web3/actions.js
  utils/enums.js
  utils/web3.js
Labels: CheckNeeded!

#541 fix/25005/chat_adaptive fix messages, messages/_id, messagesList
  components/app/pages/messages_id/messagesList.vue
  pages/messages/_id/index.vue
  pages/messages/index.vue
Labels: CheckNeeded!

#548 Fix/25330/savings
  components/CtmModal/CtmModalConfirmDetails/index.vue
  components/CtmModal/CtmModalCreditingDeposit/index.vue
  components/CtmModal/CtmModalCreditingLoan/index.vue
  components/CtmModal/CtmModalOpenADeposit/index.vue
  components/CtmModal/CtmModalWithdrawAbout/index.vue
  pages/crediting/index.vue
  pages/savings/_id/index.vue
  pages/savings/index.vue
Labels: CheckNeeded!
