Repository WorkQuest/Website-platform, pull requests merged in 2022-06, with the labels that each got.

#716 feature/30509/validation
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
Labels: Ready for review

#723 Hide checkbox confirm mnemonic
  layouts/confirm.vue
Labels: Ready for review

#718 fix/30772/validation-quest-price
  pages/create-quest.vue
Labels: Ready for review

#720 Feature/30274/notifications
  assets/scss/vars.scss
  components/CtmModal/CtmModalPrice/index.vue
  components/app/CardEmployee.vue
  components/app/CardQuest.vue
  components/app/Header/index.vue
  components/app/PanelFilters.vue
  components/app/pages/common/userInfo.vue
  components/app/pages/profile/tabs/reviews.vue
  components/ui/BaseButton/index.vue
  components/ui/NotificationsButton/index.vue
  layouts/auth.vue
  layouts/default.vue
  layouts/guest.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  middleware/guest.js
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/my.vue
  pages/notifications/index.vue
  pages/profile/_id/index.vue
  pages/quests/index.vue
  pages/settings.vue
  pages/wallet.vue
  plugins/main.js
  store/notifications/actions.js
  store/quests/actions.js
  store/user/actions.js
  store/wallet/actions.js
  utils/notifications.js
Labels: Ready for review

#724 fix/disputes open dispute modal fix
  components/CtmModal/CtmModalOpenADispute/index.vue
  components/app/pages/settings/Profile.vue
  components/ui/NotificationsButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/my.vue
  pages/notifications/index.vue
  pages/quests/_id/index.vue
  store/notifications/actions.js
  store/quests/actions.js
  utils/notifications.js
  utils/сonstants/quests.js
Labels: in progress

#715 Fix/22528/quest status
  components/app/CardQuest.vue
  components/app/Header/index.vue
  components/app/info/index.vue
  components/app/panels/questPanel.vue
  pages/disputes/_id/index.vue
  pages/edit-quest/_id/index.vue
  pages/messages/_id/index.vue
  pages/my.vue
  pages/quests/_id/index.vue
  store/quests/actions.js
  store/quests/mutations.js
  store/quests/state.js
  utils/сonstants/quests.js
Labels: in progress

#722 Reports
  components/CtmModal/CtmModalReport/index.vue
  components/CtmModal/index.vue
  components/app/pages/common/userInfo.vue
  components/app/panels/questPanel.vue
  components/ui/BaseButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  store/modals/modals.js
  store/user/actions.js
  utils/enums.js
Labels: in progress

#726 feature/31342/get_wusd
  components/CtmModal/CtmModalBuyWQT/index.vue
  components/CtmModal/CtmModalGetWUSD/index.vue
  components/CtmModal/CtmModalTransactionReceipt/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/collateral/index.vue
  pages/lending/index.vue
  plugins/main.js
  store/collateral/actions.js
  store/oracle/actions.js
  store/oracle/getters.js
  store/oracle/mutations.js
  store/oracle/state.js
  store/wallet/actions.js
  utils/enums.js
  utils/wallet.js
Labels: in progress

#731 feature/29787/fix-chats
  components/CtmModal/CtmModalChatCreate/index.vue
  components/app/pages/messages_id/messagesList.vue
  pages/messages/_id/index.vue
  pages/messages/index.vue
  store/chat/actions.js
  store/chat/mutations.js
Labels: Ready for review

#732 feature/29787/admin-in-chat
  components/CtmModal/CtmModalChatCreate/index.vue
  components/app/pages/messages_id/messagesList.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/messages/index.vue
  store/chat/actions.js
Labels: Ready for review

#734 fix/31804/chat-fixes
  components/CtmModal/CtmModalChatCreate/index.vue
  components/app/Header/index.vue
  components/app/pages/messages_id/messagesList.vue
  components/app/pages/quests_id/WorkersList.vue
  components/ui/ChatMenu/index.vue
  pages/messages/_id/index.vue
  pages/messages/index.vue
  store/chat/actions.js
  utils/enums.js
  utils/сonstants/chat.js
Labels: Ready for review

#736 feature/29787/change-tab-namme
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
Labels: Ready for review

#737 Feature/31823/statuses
  components/CtmModal/CtmModalSendARequest/index.vue
  components/app/CardQuest.vue
  components/app/info/index.vue
  components/app/pages/quests_id/WorkersList.vue
  components/app/panels/questPanel.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/create-quest.vue
  pages/messages/_id/index.vue
  pages/my.vue
  pages/quests/_id/index.vue
  store/quests/actions.js
  store/quests/getters.js
  store/quests/mutations.js
  store/quests/state.js
  utils/images.js
  utils/сonstants/quests.js
Labels: Ready for review

#739 fixes steps of payment for dispute
  pages/quests/_id/index.vue
  store/disputes/actions.js
Labels: Ready for review

#740 Feature/30717/fix-resend-button
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/sign-in.vue
Labels: Unresolved comments

#744 feature/32090/new-wqt-icon
  assets/img/ui/wqt-logo.svg
  components/ui/BaseDD/index.vue
Labels: Ready for review

#745 feature/32093/footer-links
  components/CtmModal/CtmModalPrivacy/index.vue
  components/app/Footer/index.vue
  utils/сonstants/footer.js
Labels: Ready for review

#748 feature/32096/text
  components/CtmModal/CtmModalPrivacy/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/collateral/index.vue
  pages/wallet.vue
Labels: Ready for review

#752 feature/31342/collateral
  components/CtmModal/CtmModalGetWUSD/index.vue
  components/ui/Slider/index.vue
  components/ui/Slider/model.js
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/collateral/index.vue
  plugins/vee-validate.js
  store/oracle/state.js
Labels: Ready for review

#754 fix/32283/style-checkbox
  pages/create-quest.vue
Labels: Ready for review

#753 fix/32278/2fa-on-quests edit quest 2fa check and redirects
  components/CtmModal/CtmModalSecurityCheck/index.vue
  middleware/employer-role.js
  pages/edit-quest/_id/index.vue
  pages/quests/_id/index.vue
  store/user/mutations.js
Labels: Unresolved comments, Ready for review

#760 fix/32279/adaptive-notifications
  pages/notifications/index.vue
Labels: Ready for review

#755 fix/32282/style-dd
  components/app/panels/questPanel.vue
Labels: Ready for review

#762 fix/32413/username-header
  components/app/Header/index.vue
Labels: Ready for review

#770 fix/32434/edit-quest-raising
  pages/edit-quest/_id/index.vue
Labels: Ready for review

#769 fix/32390/fix-stars-disputes
  pages/disputes/_id/index.vue
  pages/disputes/index.vue
  store/disputes/actions.js
  store/disputes/mutations.js
Labels: Ready for review
