Repository WorkQuest/Website-platform, pull requests merged in 2022-04, with the labels that each got.

#529 fix/23485/notifications-fix
  components/CtmModal/CtmModalChangeRoleWarning/index.vue
  components/CtmModal/CtmModalSendARequest/index.vue
  components/app/Header/index.vue
  components/app/pages/messages_id/messagesList.vue
  components/ui/NotificationsButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/messages/index.vue
  pages/notifications/index.vue
  pages/quests/_id/index.vue
  store/quests/getters.js
  store/user/actions.js
  utils/enums.js
Labels: CheckNeeded!

#551 Fix/25082/change profile from chat
  components/app/pages/messages_id/messagesList.vue
Labels: CheckNeeded!

#550 fix/25093/fix-reactivity-for-dates
  assets/img/lang/zh_cn.svg
  components/app/Header/index.vue
  components/app/panels/questPanel.vue
  components/ui/NotificationsButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  nuxt.config.js
  pages/mining/_id/graphics_data.vue
  pages/mining/_id/index.vue
  pages/notifications/index.vue
  pages/pension/my/index.vue
  pages/wallet.vue
Labels: CheckNeeded!

#567 Fix disable input
  components/ui/BaseInput/index.vue
Labels: bug

#566 Fix Dropdown geospatial WQ
  components/app/pages/settings/Profile.vue
Labels: bug

#571 Fix selecting and updating address
  components/app/pages/settings/Profile.vue
  pages/settings.vue
  store/referral/actions.js
Labels: CheckNeeded!

#572 Fix/25607/zero check
  components/CtmModal/CtmModalApplyForAPension/index.vue
  components/CtmModal/CtmModalChangePercent/index.vue
  components/CtmModal/CtmModalGetWUSD/index.vue
  plugins/main.js
  plugins/vee-validate.js
Labels: CheckNeeded!

#570 fix/25005/adaptive-on-chat-page
  components/app/pages/messages_id/messagesList.vue
  pages/messages/_id/index.vue
  pages/messages/index.vue
Labels: CheckNeeded!

#577 fix/25607/zero-check
  components/CtmModal/CtmModalApplyForAPension/index.vue
  components/CtmModal/CtmModalChangePercent/index.vue
  plugins/vee-validate.js
Labels: CheckNeeded!

#576 feature/26361/settings-visibility-restrictions
  components/app/pages/settings/Advanced.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/settings.vue
  utils/enums.js
Labels: CheckNeeded!

#526 Upgrade/bridge refactoring
  .github/workflows/main.yml
  components/CtmModal/CtmModalBuyAuction/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalStatus/index.vue
  components/CtmModal/CtmModalSwap/index.vue
  components/CtmModal/CtmModalSwapInfo/index.vue
  components/CtmModal/CtmModalWithdrawInfo/index.vue
  components/app/Footer/index.vue
  components/app/Header/index.vue
  components/app/info/emptyData.vue
  components/ui/BaseTable/index.vue
  components/ui/Loader/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  nuxt.config.js
  pages/bridge/index.vue
  pages/pension/my/index.vue
  plugins/main.js
  store/bridge/actions.js
  store/bridge/getters.js
  store/bridge/mutations.js
  store/bridge/state.js
  store/defi/actions.js
  store/defi/getters.js
  store/defi/mutations.js
  store/defi/state.js
  store/web3/actions.js
  store/web3/getters.js
  store/web3/mutations.js
  store/web3/state.js
  utils/bridge-constants.js
  utils/enums.js
  utils/web3.js
Labels: CheckNeeded!

#552 Fix/25080/display dropdown open display in chat
  components/ui/ChatMenu/index.vue
  pages/messages/index.vue
  pages/quests/_id/index.vue
Labels: CheckNeeded!

#583 Add remember authorization
  layouts/auth.vue
  pages/confirm.vue
  pages/role.vue
  pages/sign-in.vue
  store/user/actions.js
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
Labels: CheckNeeded!

#580 Fix style btn filters
  assets/scss/vars.scss
  components/app/panels/filters.vue
  components/ui/BaseButton/index.vue
  components/ui/BaseDD/index.vue
  components/ui/BaseFilterDD/index.vue
Labels: CheckNeeded!

#584 Fix style
  components/app/panels/filters.vue
Labels: CheckNeeded!

#585 Fix tab my quest employee
  pages/my.vue
Labels: CheckNeeded!

#589 fix/22896/fix-localization-files added missing localization keys
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
Labels: CheckNeeded!

#549 Feature/19544/quests to contracts
  .github/workflows/main.yml
  abi/abi.js
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalMakeDeposit/index.vue
  components/CtmModal/CtmModalSecurityCheck/index.vue
  components/CtmModal/CtmModalSendARequest/index.vue
  components/app/CardQuest.vue
  components/app/info/index.vue
  components/app/pages/quests_id/WorkersList.vue
  components/app/panels/questPanel.vue
  components/ui/ChatMenu/index.vue
  components/ui/QuestDD/index.vue
  components/ui/SpecializationsSelector/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  nuxt.config.js
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/my.vue
  pages/quests/_id/index.vue
  pages/quests/index.vue
  pages/workers/index.vue
  plugins/main.js
  plugins/vee-validate.js
  store/google-map/actions.js
  store/quests/actions.js
  store/wallet/actions.js
  utils/enums.js
  utils/quests-constants.js
  utils/wallet.js
Labels: Need back

#560 Feature/25736/add info wallet
  abi/abi.js
  components/CtmModal/CtmModalApplyForAPension/index.vue
  components/CtmModal/CtmModalChangePercent/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalMakeDeposit/index.vue
  components/CtmModal/CtmModalTakeWithdraw/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/pension/my/index.vue
  pages/wallet.vue
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
  store/wallet/actions.js
Labels: CheckNeeded!

#558 fix/25969/add-tokens-in-wallet
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalTransactionSend/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/wallet.vue
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
  store/wallet/actions.js
  store/wallet/getters.js
  store/wallet/mutations.js
  store/wallet/state.js
  utils/enums.js
  utils/wallet.js
Labels: CheckNeeded!

#590 Fix/26768/hidden scroll
  layouts/default.vue
  layouts/guest.vue
Labels: CheckNeeded!

#591 fix/25080/display-dropdown
  components/app/pages/quests_id/WorkersList.vue
  components/ui/ChatMenu/index.vue
  store/chat/actions.js
Labels: CheckNeeded!

#586 feature/26612/authorization_tokens
  plugins/axios.js
Labels: CheckNeeded!

#579 Feature/26042/hex-to-bech32
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/ui/BaseTable/index.vue
  package.json
  pages/staking/_id/index.vue
  pages/staking/index.vue
  pages/wallet.vue
  plugins/main.js
  plugins/vee-validate.js
  store/wallet/actions.js
Labels: CheckNeeded!

#556 Feature/25494/lending contracts
  .github/workflows/main.yml
  abi/abi.js
  components/CtmModal/CtmModalChangePercent/index.vue
  components/CtmModal/CtmModalChangeRoleReason/index.vue
  components/CtmModal/CtmModalChooseNecessarySkills/index.vue
  components/CtmModal/CtmModalConfirmDetails/index.vue
  components/CtmModal/CtmModalConfirmLoanDetails/index.vue
  components/CtmModal/CtmModalCreditingDeposit/index.vue
  components/CtmModal/CtmModalCreditingLoan/index.vue
  components/CtmModal/CtmModalGiveDeposit/index.vue
  components/CtmModal/CtmModalOpenADeposit/index.vue
  components/CtmModal/CtmModalReviewDetails/index.vue
  components/CtmModal/CtmModalSmsVerification/index.vue
  components/CtmModal/CtmModalValueSend/index.vue
  components/CtmModal/CtmModalWithdrawAbout/index.vue
  components/CtmModal/index.vue
  components/app/Footer/index.vue
  components/app/Header/index.vue
  components/ui/BaseButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  nuxt.config.js
  pages/bridge/index.vue
  pages/crediting/_id/index.vue
  pages/lending/index.vue
  pages/lending/my/index.vue
  plugins/main.js
  store/crediting/actions.js
  store/crediting/getters.js
  store/crediting/mutations.js
  store/crediting/state.js
  store/modals/modals.js
  store/oracle/actions.js
  store/oracle/getters.js
  store/oracle/mutations.js
  store/oracle/state.js
  store/wallet/actions.js
  utils/enums.js
  utils/images.js
  utils/wallet.js
Labels: in progress

#595 Download app modal
  components/CtmModal/CtmModalDownloadApp/index.vue
  components/CtmModal/index.vue
  layouts/default.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  plugins/main.js
  static/img/app/qrcode.png
  store/modals/modals.js
  store/web3/actions.js
Labels: CheckNeeded!

#596 feature/26763/add-runtime-info
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
Labels: CheckNeeded!

#597 Feature/26042/hex to bech32
  components/CtmModal/CtmModalSwap/index.vue
  components/CtmModal/CtmModalSwapInfo/index.vue
  pages/bridge/index.vue
Labels: CheckNeeded!

#601 feature/26760/change-textarea-background
  components/CtmModal/CtmModalAddLiquidity/index.vue
  components/CtmModal/CtmModalChatCreate/index.vue
  components/CtmModal/CtmModalClaim/index.vue
  components/CtmModal/CtmModalCreditingDeposit/index.vue
  components/CtmModal/CtmModalDeposit/index.vue
  components/CtmModal/CtmModalDepositOptions/index.vue
  components/CtmModal/CtmModalRaiseViews/index.vue
  components/CtmModal/CtmModalRemoveLiquidity/index.vue
  components/CtmModal/CtmModalSkills/index.vue
  components/CtmModal/CtmModalSwap/index.vue
  components/CtmModal/CtmModalSwapInfo/index.vue
  components/CtmModal/CtmModalWithdraw/index.vue
  components/CtmModal/CtmModalWithdrawInfo/index.vue
  components/CtmModal/CtmModalWithdrawOptions/index.vue
  components/app/Header/index.vue
  components/app/pages/messages_id/messagesList.vue
  components/app/pages/settings/Profile.vue
  components/ui/BaseCheckbox/index.vue
  components/ui/BaseDD/index.vue
  components/ui/BaseInput/index.vue
  components/ui/BaseTextarea/index.vue
  components/ui/CreateWallet/index.vue
  components/ui/Loader/index.vue
  components/ui/NotificationsButton/index.vue
  layouts/default.vue
  layouts/guest.vue
  pages/bridge/index.vue
  pages/collateral/index.vue
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/insuring/_id/index.vue
  pages/insuring/index.vue
  pages/lending/index.vue
  pages/messages/_id/index.vue
  pages/notifications/index.vue
  pages/pension/index.vue
  pages/pension/my/index.vue
  pages/quests/_id/index.vue
  pages/savings/_id/index.vue
  pages/savings/index.vue
  pages/sign-in.vue
  pages/staking/_id/index.vue
Labels: CheckNeeded!

#603 feature/26744/confirm-code
  pages/sign-in.vue
Labels: CheckNeeded!

#604 feature/26745/display-mnemonic
  components/CtmModal/CtmModalDownloadApp/index.vue
  components/app/BtnPasswordVisibility.vue
  components/ui/CreateWallet/index.vue
  layouts/confirmPassword.vue
Labels: CheckNeeded!

#605 Fix/22729/bridge web socket
  components/app/Header/index.vue
  pages/bridge/index.vue
  pages/wallet.vue
  plugins/connection.js
  plugins/ws.js
  store/bridge/actions.js
  store/bridge/state.js
  store/data/actions.js
  store/data/getters.js
  store/data/mutations.js
  store/data/state.js
  store/main/getters.js
  store/main/mutations.js
  store/main/state.js
  utils/bridge-constants.js
Labels: Need fix

#606 fix/26758/styles_fix bridge and guest
  layouts/guest.vue
  pages/bridge/index.vue
Labels: CheckNeeded!

#607 fix/22729/added_selectors added selector for redeem
  pages/bridge/index.vue
Labels: CheckNeeded!

#608 fix(26775): added new rules for show chat
  pages/messages/_id/index.vue
  pages/quests/_id/index.vue
Labels: CheckNeeded!

#609 Feature/26766/update profile
  pages/profile/_id/index.vue
Labels: CheckNeeded!

#612 fix/22729/bridge_web-socket fix bridge/actions subscribe logic
  store/bridge/actions.js
Labels: CheckNeeded!

#613 feature/26747/download-modal-to-wallet
  components/CtmModal/CtmModalDownloadApp/index.vue
  layouts/default.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/wallet.vue
Labels: CheckNeeded!

#611 feature/26745/display-mnemonic
  components/CtmModal/CtmModalPrivacy/index.vue
  components/app/BtnPasswordVisibility.vue
  components/ui/CreateWallet/index.vue
  middleware/auth.js
  middleware/guest.js
  pages/confirm.vue
  pages/role.vue
  pages/sign-in.vue
Labels: CheckNeeded!

#615 feature/26744/Fix-request-uncofirmed
  components/CtmModal/CtmModalPrivacy/index.vue
  layouts/auth.vue
  middleware/auth.js
  pages/index.vue
  pages/role.vue
  pages/sign-in.vue
Labels: CheckNeeded!

#616 fix/27558/wallet_selectors added selectors
  pages/wallet.vue
Labels: CheckNeeded!

#617 Feature/26753/wallet web socket
  pages/wallet.vue
  store/wallet/actions.js
Labels: Need fix

#602 refactoring mining, start to add logic for sockets
  components/CtmModal/CtmModalClaim/index.vue
  components/CtmModal/CtmModalClaimRewards/index.vue
  components/CtmModal/CtmModalDownloadApp/index.vue
  components/CtmModal/CtmModalSendARequest/index.vue
  components/CtmModal/CtmModalSwap/index.vue
  components/CtmModal/CtmModalSwapTokens/index.vue
  components/CtmModal/CtmModalValueSend/index.vue
  components/CtmModal/index.vue
  components/app/CardQuest.vue
  components/app/Footer/index.vue
  components/app/Header/index.vue
  components/app/info/index.vue
  components/app/pages/quests_id/WorkersList.vue
  components/app/panels/questPanel.vue
  components/ui/ChatMenu/index.vue
  components/ui/QuestDD/index.vue
  layouts/guest.vue
  middleware/auth.js
  package.json
  pages/bridge/index.vue
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/lending/my/index.vue
  pages/messages/_id/index.vue
  pages/mining/_id/index.vue
  pages/mining/index.vue
  pages/my.vue
  pages/quests/_id/index.vue
  pages/referral.vue
  pages/sign-in.vue
  pages/staking/index.vue
  pages/wallet.vue
  plugins/connection.js
  plugins/main.js
  store/bridge/actions.js
  store/mining/actions.js
  store/mining/getters.js
  store/mining/mutations.js
  store/mining/state.js
  store/modals/modals.js
  store/quests/actions.js
  store/user/actions.js
  store/user/getters.js
  store/user/state.js
  store/web3/actions.js
  store/web3/getters.js
  store/web3/mutations.js
  store/web3/state.js
  utils/enums.js
  utils/images.js
  utils/web3.js
  utils/сonstants/bridge.js
  utils/сonstants/footer.js
  utils/сonstants/mining.js
  utils/сonstants/quests.js
  utils/сonstants/referral.js
Labels: CheckNeeded!

#610 Feature/27539/quest draft logic
  components/CtmModal/CtmModalAreYouSure/index.vue
  components/CtmModal/CtmModalChatCreate/index.vue
  components/ui/ChatMenu/index.vue
  components/ui/FilesUploader/index.vue
  components/ui/QuestDD/index.vue
  components/ui/SpecializationsSelector/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/create-quest.vue
  pages/lending/index.vue
  pages/notifications/index.vue
  plugins/main.js
Labels: Need fix

#619 feature/26772-photo-without-text
  pages/messages/_id/index.vue
Labels: CheckNeeded!

#620 fix/26724/my_quests_request fix request in function "getUserQuests"
  pages/my.vue
  pages/profile/_id/index.vue
  store/quests/actions.js
  store/user/actions.js
Labels: CheckNeeded!

#624 feature/26772-photo-without-text hotfix
  pages/messages/_id/index.vue
  store/chat/actions.js
Labels: CheckNeeded!

#631 Feature/27921/create quest error
  assets/scss/vars.scss
  components/app/pages/settings/Profile.vue
  components/app/pages/settings/Skills.vue
  components/ui/BaseInput/index.vue
  components/ui/BaseTextarea/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/create-quest.vue
Labels: CheckNeeded!

#621 feature/28026/quest-draft-hotfix hotfix save draft
  pages/create-quest.vue
Labels: CheckNeeded!

#632 feature/27921/create-quest_error error logic fix
  pages/create-quest.vue
  utils/enums.js
Labels: CheckNeeded!
