Repository WorkQuest/Website-platform, pull requests merged in 2022-01, with the labels that each got.

#335 feature/19005/quest id page refactor
  components/CtmModal/CtmModalGallery/index.vue
  components/CtmModal/CtmModalInvitation/index.vue
  components/CtmModal/CtmModalSendARequest/index.vue
  components/GMap/index.vue
  components/app/info/index.vue
  components/app/pages/common/quests.vue
  components/app/pages/common/skills.vue
  components/app/pages/quests_id/WorkersList.vue
  components/app/pages/quests_id/employer.vue
  components/app/pages/quests_id/invitedWorkerList.vue
  components/app/pages/quests_id/respondedWorkerList.vue
  components/app/pages/quests_id/worker.vue
  components/app/panels/questPanel.vue
  components/ui/BaseDD/index.vue
  components/ui/FilesPreview/index.vue
  components/ui/QuestIdDD/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/messages/_id/index.vue
  pages/profile/_id/index.vue
  pages/quests/_id/index.vue
  pages/quests/index.vue
  pages/workers/index.vue
  plugins/injectComponents.js
  store/quests/actions.js
  store/quests/getters.js
  store/quests/mutations.js
  store/quests/state.js
  utils/enums.js
Labels: in progress

#361 hotfix/16451/quests_sort fix timeSort
  components/app/pages/common/quests.vue
  pages/my.vue
  pages/profile/_id/index.vue
  pages/quests/_id/index.vue
  pages/quests/index.vue
  store/quests/actions.js
  store/quests/getters.js
  store/quests/state.js
Labels: in progress

#375 Feature/19536/same quests
  pages/quests/_id/index.vue
  pages/quests/index.vue
Labels: CheckNeeded!

#363 fix/19479/confirm localization and confirm account fix
  layouts/confirmPassword.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/confirm.vue
  pages/sign-in.vue
Labels: in progress

#368 hotfix/18343/reviews fix reviews description length
  components/app/pages/profile/tabs/reviews.vue
Labels: CheckNeeded!

#369 Feature/18737/quest update modal
  components/CtmModal/CtmModalQuestCreated/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
Labels: in progress

#383 hotfix/19536/same_quests bug fix
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/quests/_id/index.vue
  pages/quests/index.vue
Labels: CheckNeeded!

#393 feature/20072/add-statistic-method
  layouts/auth.vue
  layouts/default.vue
  middleware/auth.js
  pages/messages/_id/index.vue
  store/user/actions.js
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
Labels: CheckNeeded!

#396 Feature/20071/message list component
  components/app/pages/messages_id/messagesList.vue
  pages/messages/_id/index.vue
  store/chat/actions.js
Labels: in progress, CheckNeeded!

#397 Hotfix/20053/profile phone
  components/app/pages/common/userInfo.vue
  pages/profile/_id/index.vue
  pages/raised-views.vue
  store/user/actions.js
  store/user/state.js
Labels: CheckNeeded!

#403 hotfix/20244/myQuests fix on profile page, added quest in favorite
  pages/my.vue
  pages/profile/_id/index.vue
Labels: CheckNeeded!

#405 hotfix/20244/myQuests bug fix
  pages/my.vue
Labels: CheckNeeded!

#402 fix/keys-to-walletjs removed session storage saving keys & mnemonics
  components/ui/CreateWallet/index.vue
  pages/sign-in.vue
  pages/wallet.vue
  store/user/actions.js
  store/wallet/actions.js
  store/wallet/getters.js
  store/wallet/mutations.js
  store/wallet/state.js
  utils/wallet.js
Labels: CheckNeeded!, Finished

#404 Fix/20283/quest action buttons adaptive
  pages/quests/_id/index.vue
Labels: CheckNeeded!

#406 fix/20295/mining-swaps fixed table data, response commit for bnb swap
  pages/mining/_id/index.vue
  store/mining/actions.js
Labels: Need fix

#408 Feature/20281/add network
  utils/enums.js
  utils/web3.js
Labels: CheckNeeded!

#409 hotfix/20331/quests_tab fix quests tab name
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/profile/_id/index.vue
Labels: CheckNeeded!

#400 fix/20161/socket-improvements
  components/CtmModal/CtmModalAreYouSure/index.vue
  components/CtmModal/CtmModalAreYouSureDeleteMember/index.vue
  components/CtmModal/CtmModalChatCreate/index.vue
  components/CtmModal/CtmModalPrivacy/index.vue
  components/CtmModal/index.vue
  components/app/pages/messages_id/messagesList.vue
  components/ui/ChatMenu/index.vue
  layouts/default.vue
  pages/messages/_id/index.vue
  pages/messages/index.vue
  plugins/connection.js
  store/chat/actions.js
  store/chat/getters.js
  store/chat/mutations.js
  store/chat/state.js
  store/modals/modals.js
  store/user/actions.js
  store/user/mutations.js
  utils/enums.js
Labels: CheckNeeded!

#410 Feature/20366/pension worknet
  abi/abi.js
  components/CtmModal/CtmModalApplyForAPension/index.vue
  components/CtmModal/CtmModalChangePercent/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalMakeDeposit/index.vue
  components/CtmModal/CtmModalTakeWithdraw/index.vue
  components/CtmModal/CtmModalWithdrawInfo/index.vue
  pages/pension/index.vue
  pages/pension/my/index.vue
  store/wallet/actions.js
  store/wallet/getters.js
  store/wallet/mutations.js
  store/wallet/state.js
  store/web3/actions.js
  utils/wallet.js
  utils/web3.js
Labels: CheckNeeded!

#415 Hotfix/20281/add network
  utils/enums.js
  utils/web3.js
Labels: CheckNeeded!

#401 Feature/15774/disputs
  components/CtmModal/CtmModalOpenADispute/index.vue
  components/app/pages/common/messages.vue
  components/app/pages/messages_id/messagesList.vue
  components/ui/ChatMenu/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/disputes/_id/index.vue
  pages/disputes/index.vue
  pages/messages/_id/index.vue
  pages/my.vue
  pages/profile/_id/index.vue
  pages/quests/_id/index.vue
  pages/quests/index.vue
  plugins/injectComponents.js
  store/chat/actions.js
  store/disputes/actions.js
  store/disputes/getters.js
  store/disputes/mutations.js
  store/disputes/state.js
  utils/enums.js
Labels: Need back, CheckNeeded!

#416 Fix/20577/quests page refactoring
  components/app/SearchWithMap/index.vue
  components/app/pages/common/questCard.vue
  components/app/panels/filters.vue
  pages/quests/index.vue
  plugins/injectComponents.js
  store/quests/actions.js
  utils/enums.js
Labels: CheckNeeded!

#417 Fix/20282/worker rank
  components/app/info/item-rating.vue
  components/app/pages/common/employeeCard.vue
  components/app/pages/common/quests.vue
  components/app/pages/quests_id/WorkersList.vue
  pages/quests/_id/index.vue
  plugins/injectComponents.js
Labels: CheckNeeded!

#418 Feature/15774/disputs
  components/CtmModal/CtmModalOpenADispute/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/quests/_id/index.vue
Labels: CheckNeeded!

#423 fix/20282/worker_rank added user rank on profile page
  assets/scss/vars.scss
  components/CtmModal/CtmModalInvitation/index.vue
  components/app/info/item-rating.vue
  components/app/pages/common/questCard.vue
  components/app/pages/common/quests.vue
  components/app/pages/common/userInfo.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/raised-views.vue
  plugins/main.js
Labels: CheckNeeded!

#419 Fix/16647/search
  components/app/SearchWithMap/index.vue
  components/app/panels/filters.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/quests/_id/index.vue
  pages/quests/index.vue
  pages/workers/index.vue
Labels: CheckNeeded!

#425 fix/20981/myQuest add sort
  pages/my.vue
Labels: CheckNeeded!

#424 Fix/16647/search
  components/app/SearchWithMap/index.vue
  components/app/panels/filters.vue
  components/ui/BaseButton/index.vue
Labels: CheckNeeded!
