Repository WorkQuest/Website-platform, pull requests merged in 2022-08, with the labels that each got.

#838 feature/31343/auction
  abi/WQAuction.js
  abi/index.js
  assets/img/ui/USD-Coin-icon.svg
  assets/scss/mixins/other.scss
  components/CtmModal/CtmModalGetWUSD/index.vue
  components/app/CardDispute.vue
  components/app/CardEmployee.vue
  components/app/CardQuest.vue
  components/app/pages/auction/AuctionCard.vue
  components/app/pages/wallet/CollateralTable.vue
  components/app/panels/RaiseViewsPanel.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/auction/index.vue
  pages/collateral/index.vue
  pages/lending/index.vue
  pages/role.vue
  pages/wallet.vue
  plugins/main.js
  store/auction/actions.js
  store/auction/mutations.js
  store/auction/state.js
  store/oracle/actions.js
  store/wallet/state.js
  utils/addresses/develop.js
  utils/addresses/index.js
  utils/addresses/master.js
  utils/addresses/stage.js
  utils/addresses/testnet.js
  utils/enums.js
  utils/images.js
  utils/locker-data.js
Labels: Ready for review

#834 Feature/34288 + 34023/bridge wallet switcher
  components/CtmModal/CtmModalBuyWQT/index.vue
  components/CtmModal/CtmModalSwap/index.vue
  components/app/Header/index.vue
  components/app/WalletSwitcher.vue
  components/ui/BaseButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/bridge/index.vue
  pages/mining/_id/index.vue
  plugins/main.js
  plugins/mixins/walletOperations.js
  store/bridge/actions.js
  store/collateral/actions.js
  store/mining/actions.js
  store/oracle/actions.js
  store/quests/actions.js
  store/user/actions.js
  store/wallet/actions.js
  store/web3/actions.js
  store/web3/getters.js
  store/web3/mutations.js
  store/web3/state.js
  utils/enums.js
  utils/wallet.js
  utils/web3.js
  utils/сonstants/bridge.js
Labels: Ready for review

#837 Feature/34289/mining wallet switcher
  components/CtmModal/CtmModalSwapTokens/index.vue
  components/CtmModal/CtmModalValueSend/index.vue
  pages/mining/_id/index.vue
  store/mining/actions.js
  utils/web3.js
  utils/сonstants/mining.js
Labels: Ready for review

#827 fix: fix v-deep
  components/CtmModal/CtmModalDownloadApp/index.vue
  components/app/pages/settings/Profile.vue
Labels: Ready for review

#822 Feature/33560/create copy btn
  components/CtmModal/CtmModalDeposit/DepositWalletAddress.vue
  components/ui/BaseButtonCopy/index.vue
  components/ui/CreateWallet/index.vue
  pages/qrCode/_address.vue
  pages/referral.vue
Labels: Ready for review

#845 Update/35201/wallet switch locales, fetch fee toast errors
  pages/mining/_id/index.vue
Labels: Ready for review

#840 update/30274/missing-notifications
  components/CtmModal/CtmModalPrivacy/index.vue
  components/CtmModal/CtmModalRegisterReferral/index.vue
  components/CtmModal/CtmModalSignWorkQuest/index.vue
  components/CtmModal/CtmModalTransactionReceipt/index.vue
  components/CtmModal/index.vue
  components/ui/NotificationsButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/notifications/index.vue
  pages/referral.vue
  pages/sign-in.vue
  pages/sign-up.vue
  store/modals/modals.js
  store/notifications/actions.js
  store/referral/actions.js
  store/referral/getters.js
  store/referral/mutations.js
  store/referral/state.js
  store/wallet/actions.js
  utils/addresses/testnet.js
  utils/notifications.js
  utils/сonstants/referral.js
Labels: in progress

#853 update/35404/wallet-save
  layouts/confirm.vue
  layouts/default.vue
  middleware/auth.js
  pages/role.vue
  pages/sign-in.vue
  store/user/actions.js
  utils/wallet.js
Labels: Ready for review

#860 Fix/35368/profile delete specialization
  components/ui/SpecializationsSelector/index.vue
  middleware/auth.js
Labels: Ready for review

#861 fix/35663/wq-modal-auth modal sign logic, toast z-index over modals
  assets/scss/main.scss
  components/CtmModal/CtmModalSignWorkQuest/index.vue
  middleware/auth.js
  pages/sign-in.vue
  utils/wallet.js
Labels: Ready for review

#855 Fix/35200/layout adaptive fix on all pages
  assets/scss/mixins/other.scss
  components/app/PanelFilters.vue
  components/ui/BaseFilterDD/index.vue
  layouts/default.vue
  layouts/guest.vue
  pages/borrow.vue
  pages/bridge/index.vue
  pages/collateral/index.vue
  pages/disputes/index.vue
  pages/insuring/_id/index.vue
  pages/insuring/index.vue
  pages/lending/index.vue
  pages/lending/my/index.vue
  pages/mining/_id/index.vue
  pages/mining/index.vue
  pages/my.vue
  pages/notifications/index.vue
  pages/profile/_id/index.vue
  pages/quests/_id/index.vue
  pages/quests/index.vue
  pages/referral.vue
  pages/retirement/index.vue
  pages/retirement/my/index.vue
  pages/role.vue
  pages/savings/_id/index.vue
  pages/savings/index.vue
  pages/staking/_id/index.vue
  pages/staking/index.vue
  pages/wallet.vue
  pages/workers/index.vue
  plugins/mixins/localNotifications.js
  utils/enums.js
Labels: Ready for review

#869 Update/35177/read all notifs btn
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/notifications/index.vue
  store/notifications/actions.js
  store/notifications/mutations.js
Labels: Ready for review

#867 fix: added max date to input date
  components/ui/BaseInput/index.vue
Labels: Ready for review

#868 fix/35487 updated address validation on mounted page
  components/app/pages/settings/Profile.vue
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
Labels: Ready for review

#794 Update/33327/delete chat
  components/CtmModal/CtmModalChatCreate/index.vue
  components/app/info/emptyData.vue
  components/app/pages/messages_id/messagesList.vue
  components/ui/ChatMenu/index.vue
  layouts/default.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/messages/_id/index.vue
  pages/messages/index.vue
  store/chat/actions.js
  store/chat/mutations.js
  utils/images.js
Labels: wontfix, Ready for review

#874 Hotfix/login with changed password
  components/CtmModal/CtmModalChangePassInSettings/index.vue
  pages/sign-in.vue
  utils/wallet.js
Labels: Ready for review

#877 fix: fix open portfolio item
  components/app/pages/profile/tabs/portfolio.vue
  components/app/pages/settings/AddForm.vue
  components/ui/BaseInput/index.vue
Labels: Ready for review

#873 Feature/error layout
  layouts/error.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
Labels: Ready for review

#878 Fix/35743/adaptive
  assets/scss/main.scss
  components/CtmModal/CtmModalReviewDetails/index.vue
  components/CtmModal/CtmModalReviewEmployer/index.vue
  components/app/CardQuest.vue
  components/app/Footer/index.vue
  components/app/pages/common/skills.vue
  components/app/pages/profile/tabs/reviews.vue
  components/app/pages/quests_id/WorkersList.vue
  components/app/pages/quests_id/starRating.vue
  components/ui/BasePager/index.vue
  components/ui/ChatMenu/index.vue
  components/ui/FilesPreview/index.vue
  layouts/default.vue
  layouts/guest.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/messages/index.vue
  pages/mining/_id/index.vue
  pages/profile/_id/index.vue
  pages/quests/index.vue
  utils/enums.js
Labels: Ready for review

#883 fix/35825/worker-response-on-invitation-quest-status
  components/app/CardQuest.vue
  components/app/info/index.vue
  pages/quests/_id/index.vue
Labels: Ready for review

#876 changed logic, separate to 1day for epmployee and 3day for worker
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/quests/_id/index.vue
  store/quests/actions.js
Labels: Ready for review

#889 fixed confirm layout for connect wallet
  pages/auction/index.vue
  pages/bridge/index.vue
  pages/collateral/index.vue
  pages/mining/_id/index.vue
  pages/mining/index.vue
  store/wallet/actions.js
  utils/enums.js
Labels: Ready for review

#885 Feature/35173/new settings edit logic
  components/CtmModal/CtmModalSecurityCheck/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/settings.vue
  store/user/actions.js
Labels: in progress

#894 Fix/36431/confirm password
  pages/auction/index.vue
  pages/bridge/index.vue
  pages/collateral/index.vue
  pages/mining/_id/index.vue
  pages/mining/index.vue
Labels: Ready for review

#895 Feature/35592/check changes in settings
  pages/settings.vue
Labels: Ready for review

#893 Feature/36223/explorer apis
  components/ui/BaseTable/index.vue
  nuxt.config.js
  pages/wallet.vue
  plugins/etherscanAPI.js
  store/wallet/actions.js
  utils/addresses/develop.js
  utils/addresses/index.js
  utils/addresses/master.js
  utils/addresses/stage.js
  utils/addresses/testnet.js
  utils/enums.js
  utils/сonstants/bridge.js
Labels: Ready for review

#907 Fix/36666/dispute card
  components/app/CardQuest.vue
  components/ui/BaseDD/index.vue
Labels: Ready for review

#908 fix/36664/long-quest-name dropdown long name selected fix
  components/ui/BaseDD/index.vue
Labels: Ready for review

#911 fix/36664/notifs-title-width fixed wide title overflow
  pages/notifications/index.vue
Labels: Ready for review

#910 fix/36522/quests-list added on all quests 2 status
  pages/quests/index.vue
Labels: Ready for review
