Repository WorkQuest/Website-platform, pull requests merged in 2022-05, with the labels that each got.

#640 feature/28026/quest-draft-hotfix
  store/user/mutations.js
Labels: CheckNeeded!

#634 feature/27911/profile-visibility
  components/app/pages/settings/Advanced.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/settings.vue
  utils/enums.js
Labels: CheckNeeded!

#635 fix/25712/fix-style-notifications
  pages/notifications/index.vue
Labels: CheckNeeded!

#646 feature/27911/profile-visibility-fix
  components/app/pages/settings/Advanced.vue
  pages/settings.vue
Labels: in progress

#645 fix/23132/Add-Review
  components/CtmModal/CtmModalAreYouSure/index.vue
  components/CtmModal/CtmModalStatus/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/quests/_id/index.vue
  utils/enums.js
Labels: in progress

#648 feature/27911/profile-visibility-fix
  components/app/pages/settings/Advanced.vue
  pages/settings.vue
Labels: CheckNeeded!

#649 fix/23132/Add-Review
  pages/quests/_id/index.vue
Labels: CheckNeeded!

#641 fix/27428/quests edit quest, 2fa close quest
  abi/WQFactory.js
  components/app/panels/questPanel.vue
  components/ui/QuestDD/index.vue
  components/ui/SpecializationsSelector/index.vue
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/quests/_id/index.vue
  plugins/main.js
  store/quests/actions.js
Labels: in progress

#654 fix/26742/invited-quests-and-profile
  pages/my.vue
  pages/profile/_id/index.vue
  store/quests/actions.js
Labels: CheckNeeded!

#651 fixed refresh tokens, refactored axios plugin, refactored user action…
  middleware/auth.js
  plugins/axios.js
  store/user/actions.js
Labels: CheckNeeded!

#657 Fix/28859/social network flow check
  components/CtmModal/CtmModalPrivacy/index.vue
  components/ui/CreateWallet/index.vue
  layouts/auth.vue
  layouts/confirmPassword.vue
  pages/role.vue
Labels: Need fix

#655 feature/27936/chat-new-options
  components/CtmModal/CtmModalChatCreate/index.vue
  components/CtmModal/CtmModalInvitation/index.vue
  components/app/pages/common/userInfo.vue
  components/ui/ChatMenu/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  store/quests/actions.js
Labels: Need fix

#656 Feature/27940/spec search
  components/ui/BaseDD/index.vue
  components/ui/BaseFilterDD/index.vue
  components/ui/SpecializationsSelector/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
Labels: in progress

#659 Feature/28928/wallet usdt token and fixes
  .github/workflows/main.yml
  abi/ERC20.js
  components/CtmModal/CtmModalGetWUSD/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/app/Header/index.vue
  nuxt.config.js
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/wallet.vue
  store/wallet/actions.js
  store/wallet/getters.js
  store/wallet/mutations.js
  store/wallet/state.js
  utils/enums.js
Labels: bug, Ready for review

#622 Feature/27932/dispute pay
  components/CtmModal/CtmModalOpenADispute/index.vue
  components/app/pages/quests_id/WorkersList.vue
  components/ui/BaseDD/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/disputes/_id/index.vue
  pages/disputes/index.vue
  pages/edit-quest/_id/index.vue
  pages/quests/_id/index.vue
  pages/wallet.vue
  plugins/main.js
  store/disputes/actions.js
  store/quests/actions.js
  utils/images.js
  utils/wallet.js
Labels: Ready for review

#643 Feature/26754/retirement web socket
  abi/WQPensionFund.js
  components/CtmModal/CtmModalApplyForAPension/index.vue
  components/CtmModal/CtmModalChangePercent/index.vue
  components/CtmModal/CtmModalMakeDeposit/index.vue
  components/CtmModal/CtmModalTakeWithdraw/index.vue
  components/CtmModal/CtmModalTransactionReceipt/index.vue
  components/CtmModal/CtmModalValueSend/index.vue
  components/CtmModal/index.vue
  components/app/Footer/index.vue
  components/app/Header/index.vue
  components/ui/Loader/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/retirement/index.vue
  pages/retirement/my/index.vue
  store/modals/modals.js
  store/retirement/actions.js
  store/retirement/getters.js
  store/retirement/mutations.js
  store/retirement/state.js
  store/wallet/actions.js
  store/wallet/getters.js
  store/wallet/mutations.js
  utils/enums.js
  utils/wallet.js
Labels: Ready for review

#662 Feature/27923/new filters for quests and both roles
  components/CtmModal/CtmModalPrice/index.vue
  components/app/PanelFilters.vue
  components/app/pages/settings/Advanced.vue
  components/app/pages/settings/Skills.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/quests/index.vue
  pages/settings.vue
  pages/workers/index.vue
  plugins/injectComponents.js
  utils/enums.js
Labels: Unresolved comments

#575 feature/26409/adding-missing-notifications
  components/app/Header/index.vue
  components/ui/NotificationsButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  middleware/guest.js
  pages/create-quest.vue
  pages/notifications/index.vue
  pages/quests/_id/index.vue
  pages/retirement/index.vue
  pages/settings.vue
  plugins/main.js
  store/chat/actions.js
  store/chat/getters.js
  store/chat/mutations.js
  store/chat/state.js
  store/notifications/actions.js
  store/notifications/getters.js
  store/notifications/mutations.js
  store/notifications/state.js
  store/user/actions.js
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
  utils/enums.js
  utils/images.js
  utils/notifications.js
Labels: Ready for review

#664 Fix/26754/retirement web socket
  components/CtmModal/CtmModalApplyForAPension/index.vue
  components/CtmModal/CtmModalValueSend/index.vue
  pages/retirement/index.vue
Labels: Ready for review

#665 feature/27923/new-filters-for-quests-and-both-roles
  components/app/CardQuest.vue
  components/app/PanelFilters.vue
  components/ui/BaseDD/index.vue
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/quests/_id/index.vue
  pages/quests/index.vue
  pages/settings.vue
  utils/enums.js
Labels: Ready for review

#667 fix/29542/spec_button BaseDD and BaseFilterDD style fix
  assets/scss/mixins/other.scss
  components/app/PanelFilters.vue
  components/ui/BaseDD/index.vue
  components/ui/BaseFilterDD/index.vue
Labels: Ready for review

#672 fix/29665/map_warnings fix localization warnings
  components/app/GMapInfoBlock.vue
Labels: Ready for review

#675 fix/26754/retirement added SetLoader false for prolong
  pages/retirement/my/index.vue
Labels: Ready for review

#677 fix/26754/retirement fix percent logic
  pages/retirement/my/index.vue
  store/retirement/actions.js
Labels: Ready for review

#680 fix/29820/2FA_refactor added refactor
  components/CtmModal/CtmModalTwoFAAuth/index.vue
Labels: Ready for review

#685 fix/26754/retirement fix logic for pension updateFee
  components/CtmModal/CtmModalApplyForAPension/index.vue
  pages/retirement/index.vue
  store/retirement/actions.js
Labels: Ready for review

#686 fix/26754/retirement fix rules in changePercent modal
  components/CtmModal/CtmModalChangePercent/index.vue
Labels: Ready for review

#687 feature/30028/watch-quests-responses
  components/app/pages/quests_id/WorkersList.vue
  pages/quests/_id/index.vue
  store/notifications/actions.js
  store/quests/actions.js
  store/quests/getters.js
  store/quests/mutations.js
  store/quests/state.js
Labels: Ready for review

#683 feature/29896/refactor-veevalidate
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  plugins/vee-validate.js
Labels: Ready for review

#688 Feature/30032/resend email
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/sign-in.vue
  store/user/actions.js
  utils/images.js
Labels: Ready for review

#692 Feature/30054/google analytics
  nuxt.config.js
  package.json
Labels: Ready for review

#695 fix/30146/change_titiles_in_settings added titles to settings
  components/app/pages/settings/Advanced.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
Labels: Ready for review

#653 Feature/27907 wallet Buy WQT modal
  abi/BuyWQT.js
  abi/index.js
  assets/img/ui/Polygon.svg
  components/CtmModal/CtmModalBuyWQT/index.vue
  components/CtmModal/index.vue
  components/ui/BaseDD/index.vue
  components/ui/Loader/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
  pages/wallet.vue
  store/modals/modals.js
  store/wallet/actions.js
  utils/enums.js
  utils/wallet.js
  utils/web3.js
  utils/сonstants/bridge.js
  utils/сonstants/commission.js
  utils/сonstants/quests.js
Labels: Need back

#689 fix/30160 Fix style create chat group
  components/CtmModal/CtmModalChatCreate/index.vue
  components/ui/ChatMenu/index.vue
Labels: Ready for review

#690 fix/30152/sms-ver-modal added timer, fixed localization, validation
  assets/img/ui/deleteError.svg
  components/CtmModal/CtmModalAreYouSureDelete/index.vue
  components/CtmModal/CtmModalSmsVerification/index.vue
  components/ui/QuestDD/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  store/user/actions.js
  utils/images.js
Labels: Ready for review

#693 Feature/27932/dispute pay
  components/CtmModal/CtmModalOpenADispute/index.vue
  pages/quests/_id/index.vue
  store/disputes/actions.js
Labels: Ready for review

#700 feature/27932/Dispute-pay added warning pay modal
  components/CtmModal/CtmModalStatus/index.vue
  pages/quests/_id/index.vue
Labels: Ready for review

#702 fix/29891/create-quest_error fix logic for scroll
  pages/create-quest.vue
Labels: Ready for review

#698 Feature/30032/resend email
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/sign-in.vue
  pages/sign-up.vue
Labels: Ready for review

#701 fix/30152/sms-ver-modal fixed response
  components/CtmModal/CtmModalSmsVerification/index.vue
Labels: Ready for review

#679 feature/25619/referral
  components/CtmModal/CtmModalReferralClaim/index.vue
  components/CtmModal/CtmModalRegisterReferral/index.vue
  components/CtmModal/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/referral.vue
  store/oracle/actions.js
  store/referral/actions.js
  store/user/getters.js
  utils/сonstants/referral.js
Labels: Ready for review

#705 Fix/30301/bridge worknet max balance
  components/CtmModal/CtmModalSwap/index.vue
  utils/web3.js
Labels: Ready for review

#703 Fix/30237/profile transitions
  components/CtmModal/CtmModalChatCreate/index.vue
  components/CtmModal/CtmModalReviewDetails/index.vue
  components/app/pages/profile/tabs/reviews.vue
  components/app/pages/quests_id/WorkersList.vue
  pages/messages/index.vue
  pages/profile/_id/index.vue
Labels: Ready for review

#709 feature/30509/textarea
  components/CtmModal/CtmModalInvitation/index.vue
  components/CtmModal/CtmModalSendARequest/index.vue
  components/app/pages/settings/Profile.vue
  pages/create-quest.vue
  pages/edit-quest/_id/index.vue
Labels: Ready for review

#712 hotfix/30611/hide-store-modals
  layouts/default.vue
  pages/wallet.vue
Labels: Ready for review

#711 fix/30237/profile-transitions bugfix
  components/CtmModal/CtmModalReviewDetails/index.vue
  components/app/Header/index.vue
  components/app/pages/profile/tabs/reviews.vue
  components/ui/NotificationsButton/index.vue
  pages/messages/index.vue
  pages/notifications/index.vue
  store/notifications/actions.js
  utils/images.js
Labels: Ready for review

#714 fix/30575 fix notification duplication
  store/notifications/actions.js
Labels: Ready for review
