Repository WorkQuest/Website-platform, pull requests merged in 2022-02, with the labels that each got.

#412 Feature/20485/staking worknet
  .github/workflows/main.yml
  abi/abi.js
  components/CtmModal/CtmModalClaimRewards/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalStake/index.vue
  components/CtmModal/CtmModalTransactionReceipt/index.vue
  components/CtmModal/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  nuxt.config.js
  pages/staking/_id/index.vue
  pages/staking/index.vue
  plugins/main.js
  store/modals/modals.js
  store/wallet/actions.js
  store/wallet/getters.js
  store/wallet/mutations.js
  store/wallet/state.js
  store/web3/actions.js
  utils/enums.js
  utils/wallet.js
  utils/web3.js
Labels: CheckNeeded!

#428 Hotfix/20281/add network
  pages/crosschain/index.vue
  pages/mining/_id/index.vue
  utils/web3.js
Labels: CheckNeeded!

#427 Fix/20601/user info
  components/app/pages/common/userInfo.vue
  components/ui/BaseButton/index.vue
Labels: CheckNeeded!

#420 fix/20363/employer-mark-in-quest-end added stars block
  components/CtmModal/CtmModalReviewEmployer/index.vue
  components/app/pages/common/questCard.vue
  components/app/pages/common/quests.vue
  components/app/pages/quests_id/starRating.vue
  components/ui/BaseTextarea/index.vue
  pages/quests/_id/index.vue
  store/user/actions.js
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
Labels: Need back, in progress

#395 fix/19997/settings-advanced-logic
  components/CtmModal/CtmModalAreYouSureDelete/index.vue
  components/CtmModal/CtmModalChangePassInSettings/index.vue
  components/CtmModal/CtmModalChangeRoleReason/index.vue
  components/CtmModal/CtmModalChangeRoleSecureCheck/index.vue
  components/CtmModal/CtmModalChangeRoleWarning/index.vue
  components/CtmModal/CtmModalDisable2FA/index.vue
  components/CtmModal/CtmModalSmsVerification/index.vue
  components/CtmModal/CtmModalTwoFAAuth/index.vue
  components/CtmModal/index.vue
  components/app/pages/settings/AddForm.vue
  components/app/pages/settings/Advanced.vue
  components/app/pages/settings/Profile.vue
  components/app/pages/settings/Skills.vue
  components/app/pages/settings/VerificationCard.vue
  layouts/default.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/settings.vue
  pages/sumsub.vue
  store/sumsub/actions.js
  store/user/actions.js
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
  utils/enums.js
Labels: Need back

#413 Feature/20418/notifications
  assets/img/ui/notification_outline_red_dot.svg
  components/CtmModal/CtmModalPrivacy/index.vue
  components/ui/NotificationsButton/index.vue
  layouts/auth.vue
  layouts/default.vue
  layouts/guest.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  middleware/auth.js
  pages/notifications/index.vue
  pages/quests/_id/index.vue
  plugins/clipboard.js
  plugins/injectComponents.js
  store/user/actions.js
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
  utils/enums.js
Labels: in progress

#438 Fix/21312/default layout v2
  components/app/Header/index.vue
  layouts/default.vue
Labels: CheckNeeded!

#439 Fix/21477/fix workplace field
  pages/settings.vue
  utils/enums.js
Labels: CheckNeeded!

#436 fix/21473/added-date-validation-settings
  components/app/pages/settings/AddForm.vue
  components/app/pages/settings/Advanced.vue
  components/app/pages/settings/Profile.vue
  components/ui/BaseInput/index.vue
  components/ui/SpecializationsSelector/index.vue
  pages/settings.vue
  plugins/vee-validate.js
Labels: CheckNeeded!

#443 fix/20352/bridge-swap
  components/CtmModal/CtmModalSwap/index.vue
  pages/crosschain/index.vue
Labels: CheckNeeded!

#445 Fix/21087/invite worker
  components/CtmModal/CtmModalInvitation/index.vue
  components/app/pages/common/userInfo.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  store/quests/actions.js
  store/quests/getters.js
  store/quests/mutations.js
  store/quests/state.js
Labels: CheckNeeded!

#432 feature/21208/register-refactor
  components/CtmModal/CtmModalConfirmPassword/index.vue
  components/CtmModal/CtmModalPrivacy/index.vue
  components/CtmModal/index.vue
  components/ui/CreateWallet/index.vue
  layouts/auth.vue
  layouts/confirmPassword.vue
  layouts/role.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  middleware/auth.js
  middleware/temp.js
  pages/confirm.vue
  pages/role.vue
  pages/sign-in.vue
  pages/sign-up.vue
  pages/wallet.vue
  plugins/axios.js
  store/modals/modals.js
  store/user/actions.js
  store/user/getters.js
  store/user/mutations.js
  store/user/state.js
  store/wallet/actions.js
  store/wallet/getters.js
  store/wallet/mutations.js
  store/wallet/state.js
  utils/enums.js
  utils/wallet.js
Labels: CheckNeeded!

#453 fix/21937/bridge_error fix address in sendTransaction()
  utils/web3.js
Labels: CheckNeeded!

#455 Fix/del notif btn for adaptive
  pages/notifications/index.vue
Labels: CheckNeeded!

#434 Fix/21312/defaut layout
  components/CtmModal/CtmModalInvitation/index.vue
  components/app/Footer/index.vue
  components/app/Header/index.vue
  components/app/pages/common/userInfo.vue
  layouts/default.vue
  pages/quests/index.vue
  pages/workers/index.vue
  utils/enums.js
Labels: CheckNeeded!

#456 fix/21937/bridge_error fix bridge
  components/CtmModal/CtmModalSwap/index.vue
  components/CtmModal/CtmModalSwapInfo/index.vue
Labels: CheckNeeded!

#429 Fix/16647/map and markers
  components/GMap/index.vue
  components/GMapInfoWindow/index.vue
  components/GMapMarker/index.vue
  components/app/GoogleMapLoader.vue
  components/app/MapBlock/index.vue
  components/app/SearchWithMap.vue
  middleware/employer-role.js
  nuxt.config.js
  package.json
  pages/quests/_id/index.vue
  pages/quests/index.vue
  pages/workers/index.vue
  plugins/injectComponents.js
  plugins/vue-google-map.js
  static/img/app/cluster_marker.svg
  static/img/app/employee_marker_blue.svg
  static/img/app/employee_marker_green.svg
  static/img/app/employee_marker_red.svg
  static/img/app/employee_marker_yellow.svg
  static/img/app/marker_blue.svg
  static/img/app/marker_red.svg
  static/img/app/quest_marker_blue.svg
  static/img/app/quest_marker_green.svg
  static/img/app/quest_marker_red.svg
  static/img/app/quest_marker_yellow.svg
  store/google-map/actions.js
  store/google-map/getters.js
  store/google-map/mutations.js
  store/google-map/state.js
  store/quests/actions.js
  store/quests/getters.js
  store/quests/mutations.js
  store/quests/state.js
  utils/enums.js
Labels: in progress

#459 fix/22157/message_invite added disable button
  components/CtmModal/CtmModalInvitation/index.vue
Labels: CheckNeeded!

#460 Fix/22121/header fix
  components/app/Header/index.vue
  components/ui/NotificationsButton/index.vue
Labels: CheckNeeded!

#463 fix/22264/wallet-send-tx
  store/wallet/actions.js
  utils/wallet.js
Labels: CheckNeeded!

#466 fix/21945/settings small fix
  components/app/pages/settings/Profile.vue
  pages/settings.vue
  store/user/actions.js
Labels: CheckNeeded!

#465 fix/22271/header_on_mining fix guest layout
  components/app/Header/index.vue
  layouts/guest.vue
  pages/crosschain/index.vue
  pages/mining/_id/index.vue
  pages/mining/index.vue
Labels: CheckNeeded!

#472 Fix/21945/settings
  components/app/pages/settings/Profile.vue
Labels: CheckNeeded!

#457 Fix/22067/modals fix
  components/CtmModal/CtmModalAreYouSureDeleteQuest/index.vue
  components/CtmModal/index.vue
  components/app/CardQuest.vue
  components/ui/QuestDD/index.vue
  pages/edit-quest/_id/index.vue
  pages/my.vue
  pages/profile/_id/index.vue
  pages/quests/_id/index.vue
  plugins/main.js
  store/modals/modals.js
Labels: CheckNeeded!

#474 Feature/21990/totp
  components/CtmModal/CtmModalSecurityCheck/index.vue
  components/app/pages/settings/Advanced.vue
  components/ui/QuestDD/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/sign-in.vue
  store/user/actions.js
Labels: CheckNeeded!

#477 fix/21312/footer social links
  components/app/Footer/index.vue
Labels: CheckNeeded!

#480 fix/21312/header fix profile__text and links
  components/app/Header/index.vue
Labels: CheckNeeded!

#470 feat/20777/quest-card-refactoring fixed index styles, added enums
  components/app/info/index.vue
  components/app/pages/quests_id/starRating.vue
Labels: CheckNeeded!

#479 fix/22617/open_dispute adaptive, character limit, close after send
  components/CtmModal/CtmModalOpenADispute/index.vue
  components/ui/BaseDD/index.vue
  components/ui/BaseTextarea/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
Labels: CheckNeeded!

#484 fix/22903/metamask_connection fix method: "connectToWallet"
  pages/mining/_id/index.vue
  store/web3/actions.js
Labels: CheckNeeded!

#464 Fix/21982/fix styles star rating
  components/CtmModal/CtmModalNeededToEnable2FA/index.vue
  components/CtmModal/CtmModalReviewEmployer/index.vue
  components/CtmModal/index.vue
  components/app/CardQuest.vue
  components/app/pages/quests_id/starRating.vue
  components/app/pages/settings/Advanced.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/my.vue
  pages/profile/_id/index.vue
  pages/quests/_id/index.vue
  pages/settings.vue
  store/modals/modals.js
  store/quests/actions.js
  store/quests/getters.js
  store/quests/mutations.js
  store/quests/state.js
  store/user/actions.js
  store/user/getters.js
  store/user/state.js
Labels: CheckNeeded!

#485 feature/22614/auction
  components/CtmModal/CtmModalBuyAuction/index.vue
  components/CtmModal/CtmModalGetWUSD/index.vue
  components/CtmModal/index.vue
  components/app/pages/auction/AuctionCard.vue
  components/ui/BaseButton/index.vue
  locales/ar.json
  locales/bn.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/zh.json
  pages/auction/index.vue
  pages/collateral/index.vue
  store/modals/modals.js
Labels: CheckNeeded!

#486 fix/22449/reviews_style fix reviews adaptive
  components/CtmModal/CtmModalReviewDetails/index.vue
  components/app/pages/profile/tabs/reviews.vue
Labels: CheckNeeded!

#487 fix/23092/star-rating-fix
  components/CtmModal/CtmModalShowImage/index.vue
  components/app/CardQuest.vue
  components/app/panels/questPanel.vue
  components/ui/FilesPreview/index.vue
  pages/my.vue
  pages/quests/_id/index.vue
Labels: CheckNeeded!

#482 fix/22767/quest-id fix buttons and some logic on quest-id
  components/app/panels/questPanel.vue
  components/ui/FilesUploader/index.vue
Labels: CheckNeeded!

#489 fix/23130/rating_profile rating logic in userInfo
  components/app/CardQuest.vue
  components/app/info/item-rating.vue
  components/app/pages/common/userInfo.vue
  locales/en.json
Labels: CheckNeeded!
